---
aws_region: us-east-1
aws_profile: root
vpc_name: "jenkins-{{ aws_region }}-vpc"
vpc_cidr: 20.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 20.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 20.0.2.0/24
    az: "{{ aws_region }}c"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
eip_name: "Jenkins-EIP"
terminate_key: "app"
terminate_value: "jenkins"
# cluster_account_id: ""
# cluster_vpc_id: ""
