---
aws_region: us-east-1
aws_profile: root
vpc_name: "jenkins-{{ aws_region }}-vpc"
vpc_cidr: 20.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 20.0.1.0/24
    az: "{{ aws_region }}a"
  private-2:
    cidr: 20.0.2.0/24
    az: "{{ aws_region }}b"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
ec2_image: ami-0ce7e47af8af35e06
ec2_instance_type: t3.micro
ec2_keypair: ""
sub_domain: ""
eip_name: "Jenkins-EIP"
# cluster_account_id: ""
# cluster_vpc_id: ""
# cluster_vpc_aws_profile: ""
# cluster_vpc_cidr: "172.20.0.0/16"
# cluster_route_table_id: ""
