---
- name: Env variable creation for Jenkins
  jenkins_script:
    script: |
      import jenkins.*
      import jenkins.model.*
      import hudson.*
      import hudson.model.*
      instance = Jenkins.getInstance()
      globalNodeProperties = instance.getGlobalNodeProperties()
      envVarsNodePropertyList = globalNodeProperties.getAll(hudson.slaves.EnvironmentVariablesNodeProperty.class)

      newEnvVarsNodeProperty = null
      envVars = null

      if ( envVarsNodePropertyList == null || envVarsNodePropertyList.size() == 0 ) {
      newEnvVarsNodeProperty = new hudson.slaves.EnvironmentVariablesNodeProperty();
      globalNodeProperties.add(newEnvVarsNodeProperty)
      envVars = newEnvVarsNodeProperty.getEnvVars()
      } else {
      envVars = envVarsNodePropertyList.get(0).getEnvVars()
      }
      envVars.put('${env_var_name}', '${env_var_value}')
      instance.save()
    args:
     env_var_name: "{{ env_var_name }}"
     env_var_value: "{{ env_var_value }}"
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_pwd }}"
  become: true